### ISSUE TITLE
Quick dumb question

### ISSUE THREAD

**Issue by jcklpe** [JoshMcguigan/hue-cli#1]
Sorry, I'm barely even a dev, I'm really more of a designer who messes around with code. 

This is written in Rust right? How do I actually use it though? Rust has to be compiled down to a binary right?

**Comment by JoshMcguigan** [comment]
Hi, thanks for the question. You are correct it needs to be compiled. 

First, you'll need to install the Rust compiler. You can do that by [following these instructions](https://www.rust-lang.org/tools/install). Next, clone this repository, then run `cargo install --force --path .` in the root directory of the repository. That command compiles and installs the `hue-cli` binary, and the `--force` just allows you to run that same command if you want to update the version you have installed. 

One word of warning though, I don't actually use this myself anymore, so if it doesn't work for you for some reason I may not be able to help much (if the issue requires actually having a hue device to troubleshoot).

**Comment by jcklpe** [comment]
@JoshMcguigan  Sure thing thanks. 

Just out of curiosity, what do you use now?

I'm weak on my code skills but I do think it would eventually be nice to have greater control over scripting my light automation. I've also looked at a couple of node or bash based projects.

**Comment by JoshMcguigan** [comment]
I moved recently and I just never setup the hue lights in my new house.

**Comment by jcklpe** [comment]
@JoshMcguigan  ah cool. I have a small apartment but I replaced every bulb in it with a smart light. But I also got a bunch of cheap philip's compatible bulbs off aliexpress called gledopto so it wasn't too expensive in addition to being a small apartment. I love it!
